### ISSUE TITLE
ShallowLearn ImportError on Ubuntu

### ISSUE THREAD

**Issue by salman-jpg** [giacbrd/ShallowLearn#15]
from shallowlearn.models import GensimFastText

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/anaconda2/lib/python2.7/site-packages/shallowlearn/models.py", line 15, in <module>
    import fasttext
  File "/home/usr/anaconda2/lib/python2.7/site-packages/fasttext/__init__.py", line 1, in <module>
    from .fasttext import skipgram
ImportError: /home/usr/anaconda2/lib/python2.7/site-packages/fasttext/fasttext.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

Tried with both 0.8.2 & 0.8.3 version of fasttext
and 0.13.4 & 1.0.1 version of gensim

Installed ShallowLearn using both 'pip' and by running the 'setup.py'

**Comment by giacbrd** [comment]
Sorry I am on vacation right now,  I will answer next week!

Il 07/mar/2017 05:43, "salman-jpg" <notifications@github.com> ha scritto:

**Comment by giacbrd** [comment]
Hi, it should be related to Anaconda + Fasttext.py , I have found this issue which is equivalent to yours https://github.com/salestock/fastText.py/issues/88

I suggest you to try with another Anaconda version

**Comment by geovedi** [comment]
try install/update `libgcc`: `conda install libgcc`.

**Comment by salman-jpg** [comment]
I was thinking of downgrading to Anaconda 4.1.1, but installing libgcc did the trick.
Thanks, @geovedi 
:)

**Comment by prakhar2b** [comment]
@giacbrd  @salman-jpg I am having the same problem.  Even downgrading anaconda doesn't seem to work
