### ISSUE TITLE
In which case would it be better to use your library?

### ISSUE THREAD

**Issue by theotheo** [giacbrd/ShallowLearn#26]
Hello! 

Sorry for a little bit strange question.
But tell me, please, in which case would it be better to use your library?

**Comment by giacbrd** [comment]
Hi,
the main advantage of this library is that is pure Python/Cython, so it has a very "integrable" API and a Scikit-learn interface. You are not limited to the CLI interface of fastText (even if there is now a Python API https://github.com/facebookresearch/fastText/tree/master/python). E.g.: you can easily use https://radimrehurek.com/gensim/models/phrases.html as features; you can evaluate the model with http://scikit-learn.org/stable/modules/model_evaluation.html; ...
One big advantage is that you can train a model incrementally (online)

There are several limitations: 
- stability (I would continue the development but I don't have much time)
- performance (even if Cython code is fast enough)
- some features are not well implemented
- ...

If you have to integrate a fastText based classifier in a Python project and incrementally train and save it, this would be a good choice.

**Comment by theotheo** [comment]
Thank you for the detailed explanation!
