### ISSUE TITLE
fastText.py model cannot be saved after de-serialization

### ISSUE THREAD

**Issue by giacbrd** [giacbrd/ShallowLearn#7]
If I load a model, with the load function, it cannot be saved with save. It misses of the file it creates after initialization.

**Comment by prakhar2b** [comment]
Hi @giacbrd , I would like to work on this. Could you brief me regarding the current status of this bug ?

**Comment by giacbrd** [comment]
I haven't worked on this. It is more inherent to fastText.py.
When you train a model from data with fastText.py, a model file is generated (it is a mandatory parameter of the train method!). 
When you load a model in memory from a pre-trained saved model nothing happens on disk, there is no way to write back the model if you change it

BUT

At the moment there is no way to do other operations on a loaded model, so this is not a real problem

I'm closing this issue because it is radically wrong!
